coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        target: 95%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "driver/tests/**"
  - "*/tests/**"
  - "**/*_tests.rs"
