[package]
name = "logi-mx-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
logi-mx-driver.workspace = true
masterror.workspace = true
gtk4.workspace = true
libadwaita.workspace = true
tracing.workspace = true
